// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using senai_inLockCodeFirst_webApi.Contexts;

#nullable disable

namespace senai_inLockCodeFirst_webApi.Migrations
{
    [DbContext(typeof(InLockContext))]
    [Migration("20231009013733_craicao-banco")]
    partial class craicaobanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.Estudio", b =>
                {
                    b.Property<Guid>("idEstudio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nomeEstudio")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idEstudio");

                    b.HasIndex("nomeEstudio")
                        .IsUnique();

                    b.ToTable("Estudio");

                    b.HasData(
                        new
                        {
                            idEstudio = new Guid("6dbf2529-4217-4c25-9ec4-86a1ccb07786"),
                            nomeEstudio = "Blizzard"
                        },
                        new
                        {
                            idEstudio = new Guid("09f050e3-cb7e-4602-bde6-8838fe5a702d"),
                            nomeEstudio = "Rockstar Studios"
                        },
                        new
                        {
                            idEstudio = new Guid("3a99355e-1d0a-4378-87bf-5a62ce7fe523"),
                            nomeEstudio = "Square Enix"
                        });
                });

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.Jogo", b =>
                {
                    b.Property<Guid>("idJogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EstudioidEstudio")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dataLancamento")
                        .HasColumnType("DATE");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("idEstudio")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nomeJogo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<decimal>("valor")
                        .HasColumnType("SMALLMONEY");

                    b.HasKey("idJogo");

                    b.HasIndex("EstudioidEstudio");

                    b.HasIndex("nomeJogo")
                        .IsUnique();

                    b.ToTable("Jogo");

                    b.HasData(
                        new
                        {
                            idJogo = new Guid("c676c175-bc38-43d4-98fa-b1412bef0d87"),
                            dataLancamento = new DateTime(2012, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            descricao = "É um jogo que contém bastante ação e é viciante, seja você um novato ou um fã.",
                            idEstudio = new Guid("6dbf2529-4217-4c25-9ec4-86a1ccb07786"),
                            nomeJogo = "Diablo 3",
                            valor = 99.00m
                        },
                        new
                        {
                            idJogo = new Guid("0816328e-ac1d-4930-9c4d-9859c3f64788"),
                            dataLancamento = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            descricao = "Jogo eletrônico de ação-aventura western.",
                            idEstudio = new Guid("09f050e3-cb7e-4602-bde6-8838fe5a702d"),
                            nomeJogo = "Red Dead Redemption II",
                            valor = 120.00m
                        });
                });

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.TipoUsuario", b =>
                {
                    b.Property<Guid>("idTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("idTipoUsuario");

                    b.HasIndex("titulo")
                        .IsUnique();

                    b.ToTable("TipoUsuario");

                    b.HasData(
                        new
                        {
                            idTipoUsuario = new Guid("b321c25a-3a83-4ab2-8c3e-c4d46408459e"),
                            titulo = "Administrador"
                        },
                        new
                        {
                            idTipoUsuario = new Guid("374390bc-01c8-43b9-8468-8bdac918afff"),
                            titulo = "Cliente"
                        });
                });

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.Usuario", b =>
                {
                    b.Property<Guid>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<Guid>("idTipoUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idUsuario");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("idTipoUsuario");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            idUsuario = new Guid("0077b03f-94ee-490f-acea-0f26a90cc73f"),
                            email = "admin@admin.com",
                            idTipoUsuario = new Guid("b321c25a-3a83-4ab2-8c3e-c4d46408459e"),
                            senha = "admin"
                        },
                        new
                        {
                            idUsuario = new Guid("15fc85fe-9644-4d8b-87d9-2cb9eec4ae6e"),
                            email = "cliente@cliente.com",
                            idTipoUsuario = new Guid("374390bc-01c8-43b9-8468-8bdac918afff"),
                            senha = "cliente"
                        });
                });

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.Jogo", b =>
                {
                    b.HasOne("senai_inLockCodeFirst_webApi.Domains.Estudio", null)
                        .WithMany("jogo")
                        .HasForeignKey("EstudioidEstudio");
                });

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.Usuario", b =>
                {
                    b.HasOne("senai_inLockCodeFirst_webApi.Domains.TipoUsuario", "tipoUsuario")
                        .WithMany()
                        .HasForeignKey("idTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoUsuario");
                });

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.Estudio", b =>
                {
                    b.Navigation("jogo");
                });
#pragma warning restore 612, 618
        }
    }
}
