// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using senai_inLockCodeFirst_webApi.Contexts;

#nullable disable

namespace senai_inLockCodeFirst_webApi.Migrations
{
    [DbContext(typeof(InLockContext))]
    [Migration("20231009123711_criacao-banco")]
    partial class criacaobanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.Estudio", b =>
                {
                    b.Property<Guid>("idEstudio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nomeEstudio")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idEstudio");

                    b.HasIndex("nomeEstudio")
                        .IsUnique();

                    b.ToTable("Estudio");

                    b.HasData(
                        new
                        {
                            idEstudio = new Guid("4a2ab164-7751-4da5-ad4f-5c56242d08df"),
                            nomeEstudio = "Blizzard"
                        },
                        new
                        {
                            idEstudio = new Guid("c40b318c-d9c9-436e-bf43-df19ec66a88f"),
                            nomeEstudio = "Rockstar Studios"
                        },
                        new
                        {
                            idEstudio = new Guid("27bbd942-09ef-4cef-8789-2e18c980ab1d"),
                            nomeEstudio = "Square Enix"
                        });
                });

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.Jogo", b =>
                {
                    b.Property<Guid>("idJogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dataLancamento")
                        .HasColumnType("DATE");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("idEstudio")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nomeJogo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<decimal>("valor")
                        .HasColumnType("SMALLMONEY");

                    b.HasKey("idJogo");

                    b.HasIndex("idEstudio");

                    b.HasIndex("nomeJogo")
                        .IsUnique();

                    b.ToTable("Jogo");

                    b.HasData(
                        new
                        {
                            idJogo = new Guid("1b336681-2030-48e2-81bb-f736dbc60838"),
                            dataLancamento = new DateTime(2012, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            descricao = "É um jogo que contém bastante ação e é viciante, seja você um novato ou um fã.",
                            idEstudio = new Guid("4a2ab164-7751-4da5-ad4f-5c56242d08df"),
                            nomeJogo = "Diablo 3",
                            valor = 99.00m
                        },
                        new
                        {
                            idJogo = new Guid("aac29d1f-2380-4933-ad55-d5b509a7c50b"),
                            dataLancamento = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            descricao = "Jogo eletrônico de ação-aventura western.",
                            idEstudio = new Guid("c40b318c-d9c9-436e-bf43-df19ec66a88f"),
                            nomeJogo = "Red Dead Redemption II",
                            valor = 120.00m
                        });
                });

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.TipoUsuario", b =>
                {
                    b.Property<Guid>("idTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("idTipoUsuario");

                    b.HasIndex("titulo")
                        .IsUnique();

                    b.ToTable("TipoUsuario");

                    b.HasData(
                        new
                        {
                            idTipoUsuario = new Guid("447efed8-11e8-4cd9-a7de-f16d4e9defb2"),
                            titulo = "Administrador"
                        },
                        new
                        {
                            idTipoUsuario = new Guid("002437fc-eebb-4cce-8572-43cc0e238a89"),
                            titulo = "Cliente"
                        });
                });

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.Usuario", b =>
                {
                    b.Property<Guid>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<Guid>("idTipoUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idUsuario");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("idTipoUsuario");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            idUsuario = new Guid("d2d855f0-4c82-487f-a84e-1bc1b2824561"),
                            email = "admin@admin.com",
                            idTipoUsuario = new Guid("447efed8-11e8-4cd9-a7de-f16d4e9defb2"),
                            senha = "admin"
                        },
                        new
                        {
                            idUsuario = new Guid("a0a0d8b0-c68f-4b83-9e2f-bee87e4084b5"),
                            email = "cliente@cliente.com",
                            idTipoUsuario = new Guid("002437fc-eebb-4cce-8572-43cc0e238a89"),
                            senha = "cliente"
                        });
                });

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.Jogo", b =>
                {
                    b.HasOne("senai_inLockCodeFirst_webApi.Domains.Estudio", "estudio")
                        .WithMany("jogo")
                        .HasForeignKey("idEstudio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estudio");
                });

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.Usuario", b =>
                {
                    b.HasOne("senai_inLockCodeFirst_webApi.Domains.TipoUsuario", "tipoUsuario")
                        .WithMany()
                        .HasForeignKey("idTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoUsuario");
                });

            modelBuilder.Entity("senai_inLockCodeFirst_webApi.Domains.Estudio", b =>
                {
                    b.Navigation("jogo");
                });
#pragma warning restore 612, 618
        }
    }
}
